// All the Card Hand Variables are Present in this Document

var yourCurrentCardIs = "Your Current Card = ";
var yourPreviousCardIs = "Your Previous Card = ";
let labelRoyalFlush = "You Have a Royal Flush!";
let labelStraightFlush = "You Have a Straight Flush!";
let labelFourOfKind = " You Have Four of a Kind!";
let labelFullHouse = "You Have a Full House!";
let labelFlush = "You Have a Flush!";
let labelStraight = "You Have a Straight!";
let labelThreeOfKind = "You Have Three of a Kind!";
let labelTwoPair = "You Have a Two Pair!";
let labelOnePair = "You Have a Pair!";
let labelNoHand = "You Have No Hand!";
let royalFlushClubs = ["10C", "AC", "JC", "KC", "QC"];
let royalFlushDiamonds = ["10D", "AD", "JD", "KD", "QD"];
let royalFlushHearts = ["10H", "AH", "JH", "KH", "QH"];
let royalFlushSpades = ["10S", "AS", "JS", "KS", "QS"];
let straightFlushClubsKing = ["10C", "9C", "JC", "KC", "QC"];
let straightFlushClubsQueen = ["10C", "8C", "9C", "JC", "QC"];
let straightFlushClubsJack = ["10C", "7C", "8C", "9C", "JC"];
let straightFlushClubsTen = ["10C", "6C", "7C", "8C", "9C"];
let straightFlushDiamondsKing = ["10D", "9D", "JD", "KD", "QD"];
let straightFlushDiamondsQueen = ["10D", "8D", "9D", "JD", "QD"];
let straightFlushDiamondsJack = ["10D", "7D", "8D", "9D", "JD"];
let straightFlushDiamondsTen = ["10D", "6D", "7D", "8D", "9D"];
let straightFlushHeartsKing = ["10H", "9H", "JH", "KH", "QH"];
let straightFlushHeartsQueen = ["10H", "8H", "9H", "JH", "QH"];
let straightFlushHeartsJack = ["10H", "7H", "8H", "9H", "JH"];
let straightFlushHeartsTen = ["10H", "6H", "7H", "8H", "9H"];
let straightFlushSpadesKing = ["10S", "9S", "JS", "KS", "QS"];
let straightFlushSpadesQueen = ["10H", "8H", "9H", "JH", "QH"];
let straightFlushSpadesJack = ["10S", "7S", "8S", "9S", "JS"];
let straightFlushSpadesTen = ["10S", "6S", "7S", "8S", "9S"];